LogFile : /var/log/cpanel.log


# cookie session
CookieName: PHPSESSID
Gclifetime: 3600
CookieLifeTime: 3600
EnableSetCookie: true


# email
Alias: cpanl
Domain: dm.aliyuncs.com
RegionId: cn-hangzhou
AccessKeyId: LTAIG47RA2EJ06qP
AccessKeySecret: jmEqG2mrGxXNpGSkTB6lWYY9xdUnfN
AccountName: send@mail.0x8c.com
ReplyAddress: zhangyuan8087@gmail.com